### ISSUE TITLE
Scala 2.12 support?

### ISSUE THREAD

**Issue by sjoerdmulder** [kamon-io/kamon-spray#6]
Tried to upgrade to scala 2.12 for our project, because of the new 2.12.3 release. All other Kamon modules we use seem to have been published with 2.12, `kamon-spray` seems to be lacking it for now.

**Comment by sjoerdmulder** [comment]
Ahhh... just realized that Spray actually doesn't have 2.12 support since it's EOL and people are recommended to move to Akka HTTP. Ignore this issue then ;)

**Comment by ivantopo** [comment]
:D, I was just about to say that!
